feat: Criando endpoint de opção
juserrrrr/4vote-api pull request #25
Opened 2024-06-07 23:40 UTC by naylane

2024-06-08 20:42 UTC, juserrrrr requested changes
Tem algumas mudanças, como criar o update-opcao.dto dentro da pasta dto, Remoção de algumas coisas  que não vai precisar, e alteração de um campos no controller, para o novo dto de update criado, de resto, tudo ok!

2024-06-08 20:42 UTC, juserrrrr commented on src/opcao/dto/create-opcao.dto.ts
Coloca a validação no DTO, pro nest ser capaz de validar antes de tentar fazer realmente a query, dá uma olhada em class-validator nestjs

2024-06-08 20:42 UTC, juserrrrr commented on src/opcao/opcao.controller.ts
Ao invés de passar o Partial, para o update, cria um arquivo na pasta dto também, como update-opcao.dto.ts, e lá dentro tua cria uma classe, por exemplo UpdateOpcaoDto e dá um extendens usando PartialType(CreateOpcaoDto), pra seguir o padrão do nestjs. Na hora de passar em @ Put, o UpdateOpcaoDto, passa a classe que acabou de criar para o update

2024-06-08 20:42 UTC, juserrrrr commented on src/opcao/opcao.service.ts
> +  private opcoes: Opcao[] = [];
Pode tirar a estrutura de dados, a lista, não vai precisar, ao invés de disso vai usar o PrismaService aqui

2024-06-08 20:42 UTC, juserrrrr commented on src/opcao/opcao.service.ts
> +  private idCounter = 1;
Pode remover o idNumber também e deixar somente o prisma, como falei acima, mas se preferir, pode deixar sem nada

2024-06-08 20:42 UTC, juserrrrr commented on src/opcao/opcao.service.ts
Pode apagar oq tem dentro da lógica de cada função e colocar somente uma string de retorno, return "Aqui retorna todas as opções", "Aqui cria uma opção" enfim, somente pra ter a estrutura pronta do endpoint

2024-06-09 13:38 UTC, sarinhasf commented on src/opcao/opcao.service.ts
não sei se entendi muito bem, então no service as funções não fariam nada? so retorna string?

2024-06-09 14:37 UTC, sarinhasf commented on src/opcao/dto/create-opcao.dto.ts
ok

2024-06-09 16:02 UTC, juserrrrr commented on src/opcao/opcao.service.ts
Vai fazer, só que no momento ainda não precisa, pq aqui vão ficar querys sala e no momento ainda não estamos trabalhando na lógica das regras de negócio

2024-06-10 16:35 UTC, juserrrrr approved these changes
Ok

2024-06-10 22:12 UTC, Fernanda-Marinho approved these changes
ok

2024-06-10 22:12 UTC, merged