add and fix vote endpoint
juserrrrr/4vote-api pull request #33
Opened 2024-06-16 05:08 UTC by Fernanda-Marinho

Aqui eu adicionei o endpoint de voto
![image](https://github.com/juserrrrr/4vote-api/assets/98289412/9ccfd07d-a0e8-48c8-a7ac-8d16d9f60b3f)

2024-06-16 05:16 UTC, Fernanda-Marinho commented
Adicionei o endpoint de tag_pesquisa
![image](https://github.com/juserrrrr/4vote-api/assets/98289412/76cc3aa2-95e4-4b1c-9596-be304b79e4c2)

2024-06-16 05:31 UTC, Fernanda-Marinho commented
Adicionei o endpoint de Tag
![image](https://github.com/juserrrrr/4vote-api/assets/98289412/fc62068b-2010-41aa-ad36-7d08c33d64a5)

2024-06-16 05:58 UTC, Fernanda-Marinho commented
Adicionei o endpoint de opcao_votada e fiquei na dúvida do que fazer com o 'id_voto'
![image](https://github.com/juserrrrr/4vote-api/assets/98289412/75143767-aa8d-4465-bd6e-540a928fa91e)

2024-06-16 18:00 UTC, juserrrrr requested changes
Fazer as correções citadas nos arquivos e quando for um nome separado pro espaço, opcao votada, usa opcaoVotada ou opcao-votada. Dando preferencia pela primeira opção.

2024-06-16 18:00 UTC, juserrrrr commented on src/voto/voto.service.ts
Descartar interface

2024-06-17 03:17 UTC, juserrrrr approved these changes

2024-06-17 20:34 UTC, mendes658 approved these changes

2024-06-17 20:35 UTC, merged